server:
  port: 8081
spring:
  application:
    name: sens-user-web
  main:
    allow-bean-definition-overriding: true
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  eureka:
    enabled: true

sens:
  # 全局限流
  ratelimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # IP限流
  iplimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制15个请求
    limit: 15
  # token交互方式
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 你的appKey
  # 第三方社交登录配置
  social:
    # 前端回调登录地址
    callbackFeUrl: http://127.0.0.1:9999/login
    # 前端绑定账号回调地址
    callbackFeRelateUrl: http://127.0.0.1:9999/relate
    # github
    github:
      clientId: 你的clientId
      clientSecret: 你的clientSecret
      callbackUrl: http://127.0.0.1:8888/sens/social/github/callback
    # qq
    qq:
      appId: 你的appId
      appKey: 你的appKey
      callbackUrl: http://127.0.0.1:8888/sens/social/qq/callback
    # weibo
    weibo:
      appKey: 你的appKey
      appSecret: 你的appSecret
      callbackUrl: http://127.0.0.1:8888/sens/social/weibo/callback


# 忽略鉴权url
ignored:
  urls:
    - /sens/actuator/**
    - /sens/admin/**
    - /editor-app/**
    - /sens/act/**
    - /sens/dictData/getByType/**
    - /sens/email/sendResetCode
    - /sens/email/resetByEmail
    - /sens/file/view/**
    - /sens/social/**
    - /sens/ws/**
    - /sens/user/regist
    - /sens/user/smsLogin
    - /sens/user/resetByMobile
    - /sens/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /sens/test/**
    - /user/**